// <auto-generated />
using System;
using BloodLink.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApplication4.Migrations
{
    [DbContext(typeof(BloodLinkContext))]
    [Migration("20260123170955_AddDonationsToHospitalRequest")]
    partial class AddDonationsToHospitalRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BloodLink.Models.BloodBank", b =>
                {
                    b.Property<int>("BankID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BankID");

                    b.ToTable("bloodbanks", (string)null);
                });

            modelBuilder.Entity("BloodLink.Models.Donation", b =>
                {
                    b.Property<int>("DonationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BloodBankBankID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BloodBankBankID1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CenterName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonatedBefore")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HospitalRequestID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HospitalRequestRequestID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Medications")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecentInfection")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecentSurgery")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("DonationID");

                    b.HasIndex("BloodBankBankID");

                    b.HasIndex("BloodBankBankID1");

                    b.HasIndex("HospitalRequestID");

                    b.HasIndex("HospitalRequestRequestID");

                    b.HasIndex("UserID");

                    b.ToTable("donations", (string)null);
                });

            modelBuilder.Entity("BloodLink.Models.HospitalRequest", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("HospitalUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RequestID");

                    b.ToTable("hospitalrequests", (string)null);
                });

            modelBuilder.Entity("BloodLink.Models.OTP", b =>
                {
                    b.Property<int>("OTPID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OTPCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("OTPID");

                    b.HasIndex("UserID");

                    b.ToTable("otps", (string)null);
                });

            modelBuilder.Entity("BloodLink.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BloodLink.Models.Donation", b =>
                {
                    b.HasOne("BloodLink.Models.BloodBank", "BloodBank")
                        .WithMany()
                        .HasForeignKey("BloodBankBankID");

                    b.HasOne("BloodLink.Models.BloodBank", null)
                        .WithMany("Donations")
                        .HasForeignKey("BloodBankBankID1");

                    b.HasOne("BloodLink.Models.HospitalRequest", "HospitalRequest")
                        .WithMany()
                        .HasForeignKey("HospitalRequestID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BloodLink.Models.HospitalRequest", null)
                        .WithMany("Donations")
                        .HasForeignKey("HospitalRequestRequestID");

                    b.HasOne("BloodLink.Models.User", "User")
                        .WithMany("Donations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodBank");

                    b.Navigation("HospitalRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodLink.Models.OTP", b =>
                {
                    b.HasOne("BloodLink.Models.User", "User")
                        .WithMany("OTPs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodLink.Models.BloodBank", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("BloodLink.Models.HospitalRequest", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("BloodLink.Models.User", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("OTPs");
                });
#pragma warning restore 612, 618
        }
    }
}
